version: '3.1'

services:

  db:
    image: postgres:11
    container_name: library-migration-postgres
    restart: on-failure:2
    environment:
      POSTGRES_PASSWORD: m1gr4ti0n

  app:
    build:
      context: ../
      dockerfile: library-migration/Dockerfile
    image: ilyacyclone/otus-library-migration:0.0.1
    container_name: library-migration
    restart: on-failure:2
#    ports:
#      - 8080:8080
    stdin_open: true # --interactive , -i		Keep STDIN open even if not attached
    tty: true # --tty , -t		Allocate a pseudo-TTY
    depends_on:
      - db