version: '3.1'

services:

  library-migration-postgres:
    image: postgres:11
    container_name: library-migration-postgres
    environment:
      POSTGRES_PASSWORD: m1gr4ti0n
    networks:
      - default
#    ports:
#      - 5432:5432 # uncomment to open access to postgres from outside


  library-migration-service:
    build:
      context: ../
      dockerfile: library-migration/Dockerfile
    image: ilyacyclone/otus-library-migration:0.0.1
    container_name: library-migration
    stdin_open: true # --interactive , -i		Keep STDIN open even if not attached
    tty: true # --tty , -t		Allocate a pseudo-TTY
    depends_on:
      - library-migration-postgres
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb-service
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-migration-postgres:5432/postgres
    networks:
      - default
      - otus-library-network

networks:
  default:
  otus-library-network:
    external: true