version: '3.1'

services:

  library-migration-postgres-service:
    image: postgres:11
    container_name: library-migration-postgres
#    restart: on-failure:1
    environment:
      POSTGRES_PASSWORD: m1gr4ti0n


  library-migration-service:
#    networks:
#      - nexusnetwork
#    external_links:
#      - nexus
    build:
      context: ../
      dockerfile: library-migration/Dockerfile
    image: ilyacyclone/otus-library-migration:0.0.1
    container_name: library-migration
#    restart: on-failure:1
#    ports:
#      - 8080:8080
    stdin_open: true # --interactive , -i		Keep STDIN open even if not attached
    tty: true # --tty , -t		Allocate a pseudo-TTY
    depends_on:
      - library-migration-postgres-service
#    networks:
#      - otus-library-network
    environment:
#      - SPRING_DATA_MONGODB_HOST=mongodb-service
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library-migration-postgres-service:5432/postgres

#networks:
#  nexusnetwork:
#    external: true
#networks:
#  otus-library-network:
#    external: true