spring:
  data:
    mongodb:
      database: otus-library
      host: localhost
      port: 27047 # change from standard 27017

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  app:
    name: OTUS Library
    description: Homework for https://otus.ru Spring Developer course

logging:
  file: library.log