cyclone:
  otusspring:
    poll:
      locale: en #supports "ru" and "en"
      csv: #file name will be constructed of {basename}_{locale}.csv
        basename: /poll
        locale: en
#        separator: "," # default separator is ,
#        comment: "#" # default comment is #